### ISSUE TITLE
Please update setup.py for newer python versions

### ISSUE THREAD

**Issue by skewty** [facebookincubator/later#13]
I was expecting / hoping to see explicit support for python versions in setup.py.
I arrived here checking for python 3.12 compatibility specifically.
Perhaps a good time to move to pyproject.toml?

**Comment by fried** [comment]
I need to land a compatibility diff for 3.12 waiting for the 3.11 fixes to ship first

**Comment by fried** [comment]
With the close of #14 this is resolved. And 3.12 is supported

**Comment by skewty** [comment]
I don't see this version on PyPI?  Was something missed / delayed / postponed?

**Comment by fried** [comment]
> I don't see this version on PyPI? Was something missed / delayed / postponed?

https://github.com/facebookincubator/later/releases/tag/23.11.30 -> https://pypi.org/project/later/23.11.30/
